### ISSUE TITLE
Issue when downloading pop data with `pop_age = all`

### ISSUE THREAD

**Issue by PierreMasselot** [guyabel/wcde#4]
Sorry about the issues today. 

I also tried to download population data, and I got an error when trying to get all age groups, but the total for sex. So, I got an error doing the following:

```r
pop_data <- get_wcde(indicator = "pop", scenario = c(1:3),
  country_code = c(40, 56, 100, 756, 196, 203, 276, 208, 233, 300, 724, 246, 
    250, 191, 348, 372, 380, 440, 442, 428, 470, 528, 578, 616, 620, 642, 
    752, 705, 703, 826), 
  pop_age = "all")

Error in `dplyr::summarise()`:                                                                                         
ℹ In argument: `dplyr::bind_cols(d)`.
ℹ In group 1: `scenario = 1`.
Caused by error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 651) to match `..32` (size 0).
```

But not doing any of the following:

```r
pop_data <- get_wcde(indicator = "pop", scenario = c(1:3),
  country_code = c(40, 56, 100, 756, 196, 203, 276, 208, 233, 300, 724, 246, 
    250, 191, 348, 372, 380, 440, 442, 428, 470, 528, 578, 616, 620, 642, 
    752, 705, 703, 826), 
  pop_age = "all", pop_sex = "all")

pop_data <- get_wcde(indicator = "pop", scenario = c(1:3),
  country_code = c(40, 56), 
  pop_age = "all")
```

My suggestion would be to rely less on `dplyr` as this makes the package more vulnerable to its changes.

**Comment by guyabel** [comment]
Thanks Pierre. The problem here is not with `dplyr`. It was in the first scenario file for the UK population age data - for some reason it was empty. I have uploaded a [new version](https://github.com/guyabel/wcde/commit/092191a8e91511f7e2977cb08ee496c7431c8132#diff-caa36fad3d8406ef03c04e0d79a2ddb148514e755cbad5fcadec7424877c942f) to Github and the IIASA server, so your `get_wcde() ` should work now. I cant see any 0MB files in the directories, so hopefully this is a one off. 

I don't have the bandwidth to rewrite the package away from `dplyr` - which is fair chunk of the code. It's going to be much easier to update the `summarise()` function before its fully depreciated and live with the fact that every so often `dplyr` functions might throw a warning when their developers go through one of their [phases](https://shahronak47.wordpress.com/2022/12/03/whats-going-wrong-with-the-tidyverse/).
